---
- block: 

    - name: Load test images from Archive
      command: docker load --input "{{item.label}}_{{item.tag}}.tar"
      args:
        chdir: "/vagrant/roles/load-test-images/files"
      become: true
      with_items: "{{test_images}}"
 
  when: is_vagrant_vm  

- block: 

    - name: Copy test image tarfile to kubernetes hosts
      copy:
        src: "{{item.label}}_{{item.tag}}.tar"
        dest: "{{ tarfile_path }}"
      become: true
      with_items: "{{test_images}}"

    - name: Load test images from Archive
      command: docker load --input "{{item.label}}_{{item.tag}}.tar"
      args:
        chdir: "{{ tarfile_path }}"
      become: true
      with_items: "{{test_images}}"
 
  when: not is_vagrant_vm  

