apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-vsm-fe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-vsm-fe
    spec:
      containers:
      - name: demo-vsm-fe
        image: openebs/jiva:latest
        ports:
        - containerPort: 3260
        - containerPort: 9501
        command: ["launch"]
        args: ["controller", "--frontend", "gotgt", "--clusterIP", "10.107.12.133",  "demo-vol1"]
