apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-vol1
spec:
  storageClassName: openebs-basic
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.44.0.1:3260
    iqn: iqn.2016-09.com.openebs.jiva:demo-vol1
    lun: 1
    fsType: "ext4"
    readOnly: false
