# Operated by an Admin
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fast-ebs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: fast-ebs-sc
spec:
  accessModes:
    - ReadWriteOnce    
  resources:
    requests:
      storage: 3Gi
