# Operated by cluster admin - Acts on Storage Provider
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow-ebs-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zone: us-east-1d
  iopsPerGB: "10"
