---
- name: Install DEB packages on K8S-minion
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ deb_packages }}"
  become: true 
  delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"

- name: Install PIP packages on K8s-minion
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"
  delegate_to: "{{ groups['kubernetes-kubeminions'].0 }}"
  become: true

