---
- hosts: kubernetes-kubeminions
  
  tasks:
    - name: Check for presence of tarfiles
      shell: ls *.tar
      args:
        chdir: "{{ playbook_dir }}/roles/load-test-images/files" 
      register: tar 
      delegate_to: 127.0.0.1 

    - name: Execute load-test-images role if tarfile exists
      include_role:
        name: load-test-images
      when: tar.stdout != ""

