---
- hosts: kubernetes-kubeminions
  
  tasks:
    - name: Check for presence of tarfile
      stat: 
        path: "{{ playbook_dir }}/roles/load-test-images/files/{{ tarfile }}"
      register: tar 
      delegate_to: 127.0.0.1 

    - name: Execute load-test-images role if tarfile exists
      include_role:
        name: load-test-images
      when: tar.stat.exists is defined and tar.stat.exists

