apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tt-jctrl-resch
  namespace: default
spec:
  template:
    metadata:
      labels:
        name: e2e-tt-jctrl-resch
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: e2e-tt-jctrl-resch
        imagePullPolicy: Always
        image: openebs/m-e2e-tt-jctrl-resch:ci
      restartPolicy: Never
